# Generated by Django 3.0.14 on 2022-03-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('first_name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('status', models.CharField(choices=[('Hot', 'Hot Lead'), ('Med', 'Med Lead'), ('Grey', 'Grey Lead'), ('New', 'New Lead'), ('Success', 'Success'), ('Mark Now', 'Mark Now')], default=False, max_length=100)),
                ('assigned_to', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
