# Generated by Django 3.0.14 on 2022-03-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
