# Generated by Django 3.0.14 on 2022-03-22 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_lead_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(max_length=150)),
                ('lead_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='authentication.Lead')),
            ],
        ),
    ]
